(require 'projectile)
(projectile-global-mode)
(setq projectile-enable-caching t)

;;(setq projectile-require-project-root nil)
(setq projectile-switch-project-action 'projectile-find-dir)
;;(require 'grizzl)
;;(setq projectile-completion-system 'grizzl)
;;(setq projectile-completion-system 'default)
(if (string-equal system-type "darwin")
     (setq projectile-indexing-method 'native)
     (setq projectile-indexing-method 'alien)
)
(setq projectile-git-command "git-ls-all-files")
(require 'helm-projectile)
(helm-projectile-on)